version: '3'

volumes:
  db_vol:
    driver: local

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - db_vol:/data
      - ./pkg/db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=dev-db